train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['comb', 'mouse']

roboflow:
  workspace: konakona
  project: project2-5cejv
  version: dataset
  license: CC BY 4.0
  url: https://universe.roboflow.com/konakona/project2-5cejv/dataset/dataset